#!/bin/sh

# shellcheck disable=SC2164
cd /SERVICE || exit

CONFIG_ARGS="s|CONFIG_SERVER_HOST|${CONFIG_SERVER_HOST}|g;\
            s|CONFIG_SERVER_PORT|${CONFIG_SERVER_PORT}|g;\
            s|CONFIG_API_PREFIX|${CONFIG_API_PREFIX}|g;\
			s|CONFIG_POSTGRES_HOST|${CONFIG_POSTGRES_HOST}|g;\
        	s|CONFIG_POSTGRES_PORT|${CONFIG_POSTGRES_PORT}|g;\
        	s|CONFIG_POSTGRES_USER|${CONFIG_POSTGRES_USER}|g;\
        	s|CONFIG_POSTGRES_PASSWORD|${CONFIG_POSTGRES_PASSWORD}|g;\
        	s|CONFIG_POSTGRES_DATABASE|${CONFIG_POSTGRES_DATABASE}|g;\
        	s|CONFIG_ACCESS_TOKEN_SECRET|${CONFIG_ACCESS_TOKEN_SECRET}|g;\
        	s|CONFIG_REFRESH_TOKEN_SECRET|${CONFIG_REFRESH_TOKEN_SECRET}|g"

sed -i -e "$CONFIG_ARGS" .env

npm run start:prod

exec "$@"