version: '3'
services:
  financial_management:
    image: ngthminhdev/financial_management:${TAG}
    ports:
      - '2002:2002'
    environment:
      - CONFIG_SERVER_HOST=54.179.222.129
      - CONFIG_SERVER_PORT=2002
      - CONFIG_API_PREFIX=/api
      - CONFIG_POSTGRES_HOST=db-financial-management.c38wakeeobqx.ap-southeast-1.rds.amazonaws.com
      - CONFIG_POSTGRES_PORT=5432
      - CONFIG_POSTGTES_USER=ngthminhdev
      - CONFIG_POSTGRES_PASSWORD=uGku2WNessmtHoObjto1
      - CONFIG_POSTGRES_DATABASE=financial_management
      - CONFIG_ACCESS_TOKEN_SECRET=uGku2WNessmtHoObjto1
      - CONFIG_REFRESH_TOKEN_SECRET=uGku2WNessmtHoObjto1