name: MManagement AWS EC2 CICD  

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_push:
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      
    - name: Get build version >> tag
      id: get_version
      run: echo "::set-output name=version::$(cat src/main.ts | grep 'version' | awk '{print $(NF-1)}')"

    - name: Build Docker Image
      run: docker build -t ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_IMAGE}}:${{ steps.get_version.outputs.version }} .

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker Image
      run: docker push ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_IMAGE}}:${{ steps.get_version.outputs.version }}

  deploy:
    runs-on: ubuntu-22.04
    needs: build_and_push
    steps:
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          echo "Start deploy new instance... "
          export TAG=${{ needs.build_and_push.outputs.version }} && cd ~/services/financial_backend && chmod +x ./deploy.sh && ./deploy.sh
